### ISSUE TITLE
Process get stucked when downloading a file

### ISSUE THREAD

**Issue by Jhonsensf** [runnerty/executor-http#2]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => 
[ ] feature request
[ ] support request =>
```

**Current behavior**
When downloading a file, the interpreter tries to transform the whole output and then the process get stucked

**Expected behavior**
There should be an option in order to not to transform the output.

**Minimal reproduction of the problem with instructions**
```
"exec": 
  {
     "id":"http_default",
      "method":"GET",
      "uri":"http://somebigfile.file",
       "responseToFile":"/etc/file"
  },
```
**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Runnerty version:** 0.0.1
2.1.1

* **Operation system:**
MacOs 10.12.4

* **Node version:** `node --version` =
v10.0.0

**Comment by CarlosCarmona** [comment]
Fixed in 1.2.0 !
